# frozen_string_literal: true

source 'https://rubygems.org'
ruby '~> 3.2.0'

gem 'rails', '~> 7.2.3'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'

# Redis & Background Jobs
gem 'redis', '~> 5.3'
gem 'sidekiq', '~> 7.3'

# API & Serialization
gem 'blueprinter', '~> 1.0'
gem 'rack-cors', '~> 2.0'
gem 'jbuilder', '~> 2.11'

# Authentication & Security
gem 'devise', '~> 4.9'
gem 'devise-jwt', '~> 0.11'
gem 'pundit', '~> 2.3'
gem 'brakeman', '~> 6.1'

# External Services
gem 'httparty', '~> 0.21'
gem 'twilio-ruby', '~> 6.9'
gem 'slack-ruby-client', '~> 2.2'

# AWS Services
gem 'aws-sdk-s3', '~> 1.140'
gem 'aws-sdk-secretsmanager', '~> 1.80'

# Utilities
gem 'dry-monads', '~> 1.6'
gem 'dry-validation', '~> 1.10'
gem 'kaminari', '~> 1.2'

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.2'
  gem 'pry-byebug', '~> 3.10'
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-rails', '~> 2.23'
  gem 'rubocop-rspec', '~> 2.26'
end

group :test do
  gem 'shoulda-matchers', '~> 6.1'
  gem 'simplecov', '~> 0.22'
  gem 'webmock', '~> 3.20'
  gem 'vcr', '~> 6.2'
  gem 'rspec_junit_formatter', '~> 0.6' # For CI test reporting
end
